### ISSUE TITLE
-Wmissing-prototypes

### ISSUE THREAD

**Issue by mkannwischer** [PQClean/PQClean#108]
We are currently not including `-Wmissing-prototypes`. 

When turning it on, I found that: 
- [address.c](https://github.com/PQClean/PQClean/blob/master/crypto_sign/sphincs-shake256-128f-simple/clean/address.c) of SPHINCS doesn't include address.h - which it should
- The functions `br_range_enc32le` and `br_aes_ct64_skey_expand` in [aes.c](https://github.com/PQClean/PQClean/blob/master/common/aes.c) should be static, but are not. 
-  Frodo's [noise.c](https://github.com/PQClean/PQClean/blob/master/crypto_kem/frodokem640shake/clean/noise.c) should include [common.h](https://github.com/PQClean/PQClean/blob/master/crypto_kem/frodokem640shake/clean/common.h)
- Frodo's [utils.c](https://github.com/PQClean/PQClean/blob/master/crypto_kem/frodokem640shake/clean/util.c) should include [common.h](https://github.com/PQClean/PQClean/blob/master/crypto_kem/frodokem640shake/clean/common.h)
- Kyber's [verify.c](https://github.com/PQClean/PQClean/blob/master/crypto_kem/kyber768/clean/verify.c) should include [verify.h](https://github.com/PQClean/PQClean/blob/master/crypto_kem/kyber768/clean/verify.h)
- Frodo's prototypes of `LE_TO_UINT16` and `UINT16_TO_LE` are not matching the implementation.

Should we turn it on? I think it is useful.

**Comment by mkannwischer** [comment]
Ok, this triggered some more problems:
The builds on Windows don't like that some prototypes differ in `const`-ness from the implementation.
If I add the `const`'s, clang-tidy complains about having top level `const`'s in declarations: https://clang.llvm.org/extra/clang-tidy/checks/readability-avoid-const-params-in-decls.html

Do we want to eliminate the top level consts entirely?

**Comment by cryptojedi** [comment]
"Matthias J. Kannwischer" <notifications@github.com> wrote:
> Ok, this triggered some more problems:
> The builds on Windows don't like that some prototypes differ in `const`-ness from the implementation.
> If I add the `const`'s, clang-tidy complains about having top level `const`'s in declarations: https://clang.llvm.org/extra/clang-tidy/checks/readability-avoid-const-params-in-decls.html
> 
> Do we want to eliminate the top level consts entirely? 

Do I understand correctly that those are non-pointer arguments. If yes,
what would be the reason to mark them as const?

**Comment by mkannwischer** [comment]
Yes, see e.g. line 15 in [util.c](https://github.com/PQClean/PQClean/blob/master/crypto_kem/frodokem640shake/clean/util.c).

**Comment by dstebila** [comment]
We should not eliminate top-level const's entirely: pointers to "input" buffers should be marked const even in prototypes, and if a linter complains about that, then the linter is *wrong*.  (But I don't think clang-tidy complains about this, since we're doing it already now.)

As for const's on non-pointers, admittedly formally there is no reason for them.  I personally like them there because it can serve as a short hand to the reader that "const" = "input", "non-const" = "output".  But I won't fight for that.

So I have no objection to checks that would cause us to remove const from lines 15 and 19 of [util.c](https://github.com/PQClean/PQClean/blob/master/crypto_kem/frodokem640shake/clean/util.c), but would object to removing const from line 27 of [util.c](https://github.com/PQClean/PQClean/blob/master/crypto_kem/frodokem640shake/clean/util.c) or anywhere in [common.h](https://github.com/PQClean/PQClean/blob/master/crypto_kem/frodokem640shake/clean/common.h).

**Comment by mkannwischer** [comment]
Agree, I think I got confused by "top-level". But what you describe is exactly what I mean. I'll change that. 
Back to the original question: Any objections against -Wmissing-prototypes?

**Comment by cryptojedi** [comment]
"Matthias J. Kannwischer" <notifications@github.com> wrote:
> Agree, I think I got confused by "top-level". But what you describe is exactly what I mean. I'll change that. 
> Back to the original question: Any objections against -Wmissing-prototypes?

No, sounds like a useful warning to have.
