### ISSUE TITLE
Handle slow tests (valgrind)

### ISSUE THREAD

**Issue by thomwiggers** [PQClean/PQClean#119]
The valgrind tests are too slow, especially with SPHINC+ schemes (#118).

I would propose doing the following:

1. Tag all slow tests with some attribute
2. `if 'CI' in os.environ and not 'RUN_ANYWAY' in os.environ: raise unittest.SkipTest()`
3. Set up a daily build build that builds with 'RUN_ANYWAY=1' set.

**Comment by dstebila** [comment]
I had tried to design the [`helpers.permit_test`](https://github.com/PQClean/PQClean/blob/master/test/helpers.py#L107) function in so that we could use a single function to control which tests to run, without having to make changes in every test file.  So perhaps we can make a list in that function of slow tests and then do the check you are proposing.

**Comment by thomwiggers** [comment]
Yeah, I tried to set that up in #117 but it's not completely working yet.

**Comment by dstebila** [comment]
Also causing problems for #112

**Comment by dstebila** [comment]
Fixed by #147
