### ISSUE TITLE
Allowing non-NIST schemes

### ISSUE THREAD

**Issue by thomwiggers** [PQClean/PQClean#388]
We've each time removed schemes that were dropped from the NIST competition. @Bob10918 just very kindly contributed the updated version of the LEDAcryptKEM code, but LEDAcryptKEM had since the end of Round 2 been removed from PQClean. 

This raises the question: do we want to open up to non-NIST schemes?

## Pro

* As we won't contribute these schemes ourselves, it seems fairly low-effort initially. Going through our testing framework still benefits the code quality of the schemes subjected to it.
* We have more code

## Cons
* Inevitably, we will have to deal with maintenance of such schemes as it comes up. 
* What should we do if e.g. another attack on such a scheme is found? Immediately remove it? Or does the burden of updating the code yet again then fall to us again?

**Comment by thomwiggers** [comment]
I'm inclined to say no, we should not open up more, as we already have a fairly limited bandwidth to maintain the current schemes ourselves.

**Comment by mkannwischer** [comment]
I'm against merging non-NIST schemes. 
I don't think there is much interest in non-NIST / non-Chinese schemes at the moment. 

Having more schemes inevitably results in more maintenance work in PQClean as well as in downstream projects like https://github.com/mupq/pqm4. Sure, we could provide an easy way to filter those out, but I think the added complexity is not worth it in imho. 

Once you merge non-NIST schemes, the next logical request would be to also have XMSS and LMS. It would just require a small tweak to the API. I really don't want to go down that path.

**Comment by Bob10918** [comment]
Good morning,
first of all thank you all for your attention.
If the problem is the maintenance/update of the code, my professor (the "creator" of LEDAcrypt algorithm) says he and his team would be pleased to personally take care of the constant maintenance of the code.
Anyway, I understand this would require you to deal with all the non-NIST schemes subsequently.
I will take your last decision.
Once more, thank you for your attention and have a great day,
Emanuele Pisano
________________________________
Da: Thom Wiggers ***@***.***>
Inviato: lunedì 29 marzo 2021 10:34
A: PQClean/PQClean ***@***.***>
Cc: Emanuele Pisano ***@***.***>; Mention ***@***.***>
Oggetto: Re: [PQClean/PQClean] Allowing non-NIST schemes (#388)


I'm inclined to say no, we should not open up more, as we already have a fairly limited bandwidth to maintain the current schemes ourselves.

**Comment by dstebila** [comment]
For OQS we are focused solely on NIST schemes for now.  If things start happening outside of NIST that gain significant traction, then there would be a reason to revisit that.

**Comment by thomwiggers** [comment]
I think we've got consensus. Sorry @Bob10918, but I don't think we will be merging #387. 

I hope that the testing framework was helpful to find any issues in the code, at least.

**Comment by Bob10918** [comment]
Yes! Thank you anyway and
Have a great day,
Emanuele Pisano
________________________________
