### ISSUE TITLE
Test Makefile dependencies

### ISSUE THREAD

**Issue by cryptojedi** [PQClean/PQClean#45]
Should make sure that the Makefiles really have dependencies on all .c and .h files
and possibly the Makefile itself.

**Comment by dstebila** [comment]
It would be quite unusual to list the Makefile as a dependency of a target, I think.

In terms of .h and .c dependencies, each scheme has that in its own Makefile, and the test Makefile just calls that.  However, the test Makefile didn't force a rebuild of the individual scheme, is that what you wanted?  If so, I've now added that in a7328f8.

**Comment by thomwiggers** [comment]
II don't think we wanted that, we discussed exactly that option yesterday in the office and just having `rebuild-scheme` was and should be enough to make sure that the target was up to date.

The problem we ran into was that changes in the individual scheme files were not picked up by running the pythonized tests, because they would not trigger a rebuild. This `make` target takes care of this problem. No need for the `make clean`, *if* the `Makefile` correctly specifies the dependencies. That latter part is the crux of this issue I think; making sure that the Makefile *does* correctly specify this.

However, I think that this may be a bit overly complicated, because if you want to check that manually, you need to build a dependency tree of the C files; at that point you might as well generate the Makefile from the tree you built.

(Also not sure if e.g. automake or CMake may at that point be more suitable – are they able to do that for you?)

**Comment by thomwiggers** [comment]
We may just add this as a checkbox for the manual review process.

**Comment by cryptojedi** [comment]
Thom Wiggers <notifications@github.com> wrote:
> We may just add this as a checkbox for the manual review process.

Fairly easy to check automatically: touch each file separately and see
if make rebuilds.

**Comment by cryptojedi** [comment]
Douglas Stebila <notifications@github.com> wrote:

> It would be quite unusual to list the Makefile as a dependency of a
> target, I think.

I know for some reason it's unusual, but if you change compiler flags in
the Makefile you'd want your whole code to recompile when typing "make".
The natural way to do this to have compilation depend on the Makefile
itself.

> In terms of .h and .c dependencies, each scheme has that in its own
> Makefile, and the test Makefile just calls that.  However, the test
> Makefile didn't force a rebuild of the individual scheme, is that what
> you wanted?  If so, I've now added that in a7328f8.

Yes, that's fixed. I was just wondering if we'd want to add tests that,
for example, none of the scheme Makefiles forgets to depend on .h files.
