### ISSUE TITLE
Un-namespace API functions?

### ISSUE THREAD

**Issue by cryptojedi** [PQClean/PQClean#46]
Didn't we at some point agree that API functions shouldn't be namespaced
to avoid breaking namespacing done by the respective projects using them?

**Comment by thomwiggers** [comment]
No, I think we agreed to namespace them because they may conflict with things included by any projects that adopt code from this repo.

**Comment by cryptojedi** [comment]
Thom Wiggers <notifications@github.com> wrote:
> No, I think we agreed to namespace them because they may conflict with
> things included by any projects that adopt code from this repo.

So, looking at some projects that we want to use our code:
- SUPERCOP does not want those functions namespaced;
- pqm4 does not want those functions namespaced;
- libpqcrypto does not want those functions namespaced; and
- liboqs at the moment DOES want them namespaced, but differently.

**Comment by thomwiggers** [comment]
@cryptojedi and I talked a bit:

* people currently adopting code (e.g. SUPERCOP, pqm4, libpqcrypto, liboqs) from the NIST proposals are used to the `crypto_kem_` api without namespacing and have solutions in place to handle that. It would probably be easier for them to not change how this works if they instead want to grab code from here.
* They still would need to do the type changes, which could be slightly annoying.
* I _think_ no namespacing makes linking together multiple schemes complicated (I'm not a C packaging expert by any means).
* Possible ways forward include:
  * no namespacing
  * namespacing
  * some "mutable" way of turning off or on the namespacing (overrides, `#define` macros, whatever) from the outside
  * Provide a `nist-api.h` which contains NIST-compatible (including types) `inline` functions that wrap the namespaced scheme functions. 

We should also consider that currently the `#define` constants are currently also not namespaced and including the `api.h` from different schemes will thus not work.

It seems that this is something we should talk about in the meeting.

**Comment by dstebila** [comment]
If we go back to the original motivation, of providing good code that adopters can use in their applications/libraries, and assume that may be more than one KEM and more than one SIG selected by NIST, then it will be easiest for adopters if we provide namespaced code.  Even if it doesn't match their preferred namespacing, it is easier for them to renamespace or just accept our second namespace.  So I'm in favour of namespacing.  

If we didn't namespace, I also don't know how we'd deal with symbols that are not intended to be exported (e.g., all the functions besides the top 3 crypto\_kem\_{keypair,encaps,decaps}) but which we haven't demanded be static.

The non-namespacing of api.h is problematic.  In liboqs, we took the perspective that api.h was a local header to the implementation, and defined our own header for sharing that information between files, but this meant copying and pasting lengths, etc., which reduces maintainability.

**Comment by dstebila** [comment]
This evening I tried taking the kyber768\_clean implementation from PQClean and integrating it into liboqs master branch.  See the results in open-quantum-safe/liboqs#466.

In summary, the code from PQClean was in a good state to do this.  

- I was able to drop the entire `crypto_kem\kyber768\clean` directory into a corresponding directory in liboqs without modification (although I did delete Makefile and Makefile.Microsoft\_nmake from PQClean), and then wire this into liboqs' data structures very easily.  
- Having the PQClean symbols namespaced was indeed helpful, as I chose to keep the PQCLEAN_ namespacing on the symbols, and then just add an OQS_ namespacing wrapper around the top-level functions.  
- I easily added shim headers for fips202.h and randombytes.h mapping the calls from PQClean to the corresponding functions provided by liboqs.

I can't think of anything I'd change from PQClean.  We talked about namespacing the macros in api.h, but that wouldn't have actually been useful for me in liboqs: we have our own kem\_kyber.h file containing macros for the ciphertext etc. sizes.  Right now it's got the actual numbers in there.  If I tried to define them in terms of the macros from kyber768's api.h, which happens to include kyber768's params.h, then I now have to export all those headers in the set of public headers from liboqs, which I wouldn't want to do.

Adopting #51 would eventually be an improvement once we get to multiple implementations of the same algorithm; I'd want to revisit the OQS integration once we have two such implementations available to make sure it works fine.

I am closing this issue since I don't think there's anything more to do here.
