### ISSUE TITLE
Support for other languages (Python etc.)

### ISSUE THREAD

**Issue by HarryR** [PQClean/PQClean#5]
Hi,

 A while ago I started on a similar project to support the NIST post-quantum crypto algorithms in Python: https://github.com/HarryR/Pypqc

 I think it has similar goals to this project, but I was aiming to be able to import algorithms without having to modify them.

 Any ideas on collaborations that would be worth while?

**Comment by cryptojedi** [comment]
HaRold <notifications@github.com> wrote:
> Hi,

>  A while ago I started on a similar project to support the NIST post-quantum crypto algorithms in Python: https://github.com/HarryR/Pypqc
> 
>  I think it has similar goals to this project, but I was aiming to be able to import algorithms without having to modify them.
> 
>  Any ideas on collaborations that would be worth while?

As far as I can tell, Pypqc has two parts: C implementations and Python
wrappers. The idea of pqclean is to collect C implementations and
provide those to higher-level frameworks and libraries, so that the work
of cleaning up C code has to be done just once. What would be great is
if you could contribute clean C code to pqclean and then use the C
implementations provided by pqclean as a basis for the Python framwork.
We're certainly very happy to receive pull requests and we're also very
happy to receive feedback stating what the standalone C implementations
in pqclean would need to provide in terms of interfaces etc. to be
useful for, e.g., Python wrappers.

**Comment by thomwiggers** [comment]
As @cryptojedi stated, the intention of this project is _not_ to be a (user-aimed) library of post-quantum software, we want to provide clean, portable code such that _other projects_ can build their own nice, user-friendly wrappers around it (e.g. [liboqs](/open-quantum-safe/liboqs) or your lib) use it as a starting point for projects such as efficient platform-specific implementations (e.g. AVX2 or [pqm4](/mupq/pqm4)).

We're currently working on setting up the infrastructure; we want to build and run some basic tests on various targets, including Linux, OS X, Windows, ARM, 32-bit machines, big- and little-endian machines, etc.  We also want to do some integration sanity checking, such as making sure all the symbols are namespaced.

We're also probably open to contributions of C implementations, but that would currently involve some manual checking labour until all the automatic checks are in place (and the current implementations don't even meet our rules yet!). I'd wait a short while until this stabilizes.

The title of this issue, "Support for other languages", is however out of scope, I think, so I'll close this issue – don't let this discourage you from providing your thoughts on the things related to integrating implementations sourced from this project into python that would be within scope.
