### ISSUE TITLE
Consider renaming Kyber to ML-KEM

### ISSUE THREAD

**Issue by zugzwang** [PQClean/PQClean#557]
I am testing my implementations of both Kyber round 3 and ML-KEM.

Currently, PQClean/crypto_kem/kyber{512,768,1024} implement the NIST draft, henceforth ML-KEM. It is not clear from the documentation of the [pqcrypto_kyber crate](https://docs.rs/pqcrypto-kyber/latest/pqcrypto_kyber/) nor this repository that this is the case. If you prefer to honor the original name, I would still definitely warn that the draft is implemented.

Do note that I am not trying to nitpick on names; there is a number of currently deployed projects that use e.g. Kyber768 round 3, so confusion might arise. In all honesty I spent a while debugging under the assumption that this was kyber round 3, until I realized the lack of KDF(K' || H(c)) in encaps/decaps.

**Comment by aabmets** [comment]
@zugzwang If I remember it correctly, one does not just rename Kyber into ML-KEM, because NIST requested some tweaks to the original Kyber source code before it was standardized as ML-KEM, therefore it produces different output. ML-KEM would need to be included into this library explicitly by taking a look at what changes NIST specifically introduced to the algorithm and then including the source code into PQClean, retaining the original Kyber implementation, because there are dependencies by now and renaming Kyber to ML-KEM would definitely fuck up someones unittests or deployment pipelines or worse.

**Comment by mkannwischer** [comment]
@aabmets @zugzwang you are both correct that Kyber round 3 and Kyber as in [FIPS203.ipd](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.203.ipd) have slight differences. We currently have the latter (-ish, there is some slight differences between https://github.com/pq-crystals/kyber/tree/standard and FIPS203.ipd)  in PQClean and you can still retrieve the former at https://github.com/PQClean/PQClean/releases/tag/round3.

We don't know yet what the final FIPS203 will look like and NIST is still considering some changes that would affect testvectors. I think renaming once the final standard is out and considering everything before that as different versions of Kyber is the safest option to not cause any issues downstream.

**Comment by aabmets** [comment]
@mkannwischer If PQClean is going to rename Kyber to ML-KEM and Dilithium to ML-DSS, it would be pertinent and wise to put out a bulletin notifying of the change well before the change is implemented, so that third parties would have the opportunity to mitigate any issues that might arise from breaking compatibility.

**Comment by mkannwischer** [comment]
Noted. We have not really discussed any renaming yet. 
If we would do it, it may be a good idea two keep two copies for a while before removing the Kyber ones. 
In the long term, I'd expect consumers to switch to https://github.com/pq-code-package/ implementations of ML-KEM and ML-DSA once those are available.

**Comment by aabmets** [comment]
@mkannwischer The [PQ Code Package ML-KEM generic repo](https://github.com/pq-code-package/mlkem-c-generic) describes itself as "ML-KEM generic implementation in C from PQclean", so based on that description, it would be fair to assume that they expect PQClean team or contributors to implement the NIST ML-KEM into the PQClean project, which the PQ Code Package team then upsources into their repository. This still means that PQClean is going to be the base reference repository.

**Comment by mkannwischer** [comment]
No, https://github.com/pq-code-package/mlkem-c-generic will certainly not take the sources from PQClean. Where did you read that?

https://github.com/pq-code-package/mlkem-c-generic/pull/1 pulls in https://github.com/pq-crystals/kyber. 
And afaik the plan to to basically keep https://github.com/pq-crystals/kyber and https://github.com/pq-code-package/mlkem-c-generic in sync with as few changes as possible. There are some discussions about code sharing with other pq-code-package projects, but there is no relation to PQClean.
If anything, I'd see PQClean as a consumer of the pq-code-package, but nothing in that regard has been discussed yet.

**Comment by mkannwischer** [comment]
It was been changed now.
