### ISSUE TITLE
Secret key should not be part of test vectors

### ISSUE THREAD

**Issue by joostrijneveld** [PQClean/PQClean#93]
This came up while discussing #92; we allow people to vary secret key lengths across implementations, but our test vectors are even stricter, requiring them to be byte-wise identical. We should probably just remove the secret key from the test vector output.

**Comment by cryptojedi** [comment]
This is related to the discussion we had about test vectors (and to including secret-key size in the YAML file). Essentially it boils down to the question of when two schemes are different. We could decide that as soon as schemes produce different testvectors, including secret keys, they are different schemes. Then also the secret-key size can go back into the YAML file. Maybe that's the most consistent approach.

**Comment by dstebila** [comment]
If we have a clean and an optimized implementation of the same scheme, are they obligated to produce the same test vectors? Use the same secret key format?

**Comment by cryptojedi** [comment]
Douglas Stebila <notifications@github.com> wrote:

> If we have a clean and an optimized implementation of the same scheme,
> are they obligated to produce the same test vectors? Use the same
> secret key format?

That's sort of the question. For the moment, we can decide that the
answer is "yes" and then all kind of issues go away.

**Comment by dstebila** [comment]
Focusing on KEMs, I think there are three levels of interoperability we could use to define "being the same scheme", in increasingly levels of stringency:

- public-message-interoperable: two implementations that process each others' ciphertexts and public keys arrive at the same shared secret
- secret-key-interoperable: public-message-interoperable, plus the fact that the decapsulation code from one implementation can use the secret key output by keypair generation from another implementation
- randomness-equivalent: two implementations produce exactly the same output when run with the same randomness

RSA in SSH or TLS libraries has "public message interoperability", but may store secret keys in different formats.

AES has secret-key-interoperability, albeit not entirely, as different implementations may represent an expanded key schedule in different ways.

I'd prefer to demand only public-message-interoperability, because I think implementers should be allowed to choose between trade-offs in secret key representation.

**Comment by dstebila** [comment]
I think we've come to the conclusion that secret keys will remain part of the test vectors especially since they're part of the NIST KATs.  Any objections to closing this issue?

**Comment by thomwiggers** [comment]
Nope, let's revisit this if the issue comes up.
